image: php:8.1

pipelines:
  default:
    - parallel:
        - step:
            name: Build Testing
            image: composer:latest
            artifacts:
              - "vendor/**"
            script:
              # Install php dependencies
              - composer install --ignore-platform-reqs --optimize-autoloader
              - vendor/bin/phpunit
        - step:
            name: Lint
            script:
              - find . -name '*.php' -exec php -l {} \;
  branches:
    development:
      - parallel:
          - step:
              name: Build Testing
              image: composer:latest
              artifacts:
                - "vendor/**"
              script:
                # Install php dependencies
                - composer install --ignore-platform-reqs --optimize-autoloader
                - cp .env.example .env
                - php artisan key:generate
                - vendor/bin/phpunit
          - step:
              name: Lint
              script:
                - find . -name '*.php' -exec php -l {} \;
          - step:
              name: Deploy to Staging
              deployment: Staging
              trigger: manual
              script:
                - pipe: atlassian/ssh-run:0.4.0
                  variables:
                    SSH_USER: $SSH_USER
                    SERVER: $SSH_HOST
                    COMMAND: "cd /home/pimenvibritania/gift-card && git pull origin development && /usr/bin/php8.1 /usr/local/bin/composer install --ignore-platform-reqs --optimize-autoloader && /usr/bin/php8.1 artisan cache:clear && /usr/bin/php8.1 artisan config:cache && /usr/bin/php8.1 artisan route:cache && /usr/bin/php8.1 artisan view:cache && /usr/bin/php8.1 artisan optimize"
