image: php:8.1

pipelines:
  default:
    - parallel:
        - step:
            name: Test
            image: phpunit/phpunit
            script:
              - docker run -v $(pwd):/app --rm phpunit/phpunit tests/Feature/ExampleTest.php
            services:
              - docker
        - step:
            name: Lint
            script:
              - find . -name '*.php' -exec php -l {} \;
  branches:
    master:
      - parallel:
          - step:
              name: Test
              image: phpunit/phpunit
              script:
                - docker run -v $(pwd):/app --rm phpunit/phpunit tests/Feature/ExampleTest.php
              services:
                - docker
          - step:
              name: Security Scan
              script:
                # Run a security scan for sensitive data.
                # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
                - pipe: atlassian/git-secrets-scan:0.5.1
      - step:
          name: Deploy to Production
          deployment: Production
          trigger: manual
          script:
            - pipe: atlassian/ssh-run:0.4.0
              variables:
                SSH_USER: $SSH_USER
                SERVER: $SSH_HOST
                COMMAND: 'cd /home/pimenvibritania && mkdir testDeploy'
               
