image: php:8.1

# Doing a full clone to be able to push back to Heroku.
clone:
  depth: full

pipelines:
  branches:
    master:
      - step:
          name: Unit Tests
          caches:
            - composer
          script:
            - apt-get update && apt-get install -y unzip
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            - composer install
            - cp .env.testing .env
            - vendor/bin/phpunit --verbose --testsuite Unit
      - step:
          name: Integration Tests
          caches:
            - composer
          script:
            - apt-get update && apt-get install -y unzip
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            - composer install
            - cp .env.testing .env
            - vendor/bin/phpunit --verbose --testsuite Feature
      - step:
          name: Deploy to Heroku
          deployment: production
          script:
            - apt-get update && apt-get install -y git
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD
